'''
Convert the output from Transcript Effects to a csv with common headers for the sake of comparison.
Created on May 14, 2026

@author: pleyte
'''
import argparse
import logging
from nomenclature_comparison.variant_transcript import VariantTranscript
from collections import Counter
import json
from nomenclature_comparison.io import normalized_writer

class NormalizeTfx(object):
    '''
    classdocs
    '''
    def __init__(self):
        '''
        Constructor
        '''
        self._logger = logging.getLogger(f"nomenclature_comparison.{__name__}")        

    def _get_variant_transcript(self, j:dict):
        """
        Create VariantTrancript using a dict of Tfx values
        """
        v = VariantTranscript(j['chromosome'], j['position'], j['reference'], j['alt'], j['cdnaTranscript'])

        v.g_dot = j['sequenceVariant']        
        v.c_dot = j['cdnaNomenclature']    
        v.gene = j['gene']
        v.p_dot1 = j['proteinNomenclature1']
        v.p_dot3 = j['proteinNomenclature3']
        v.protein_transcript = j['proteinTranscript']
        v.splicing = j['splicing']
        
        return v
        
    def get_variant_transcripts(self, tfx_json_file: str) -> list[VariantTranscript]:
        """
        """
        count = Counter()
        with open(tfx_json_file, 'r') as f:
            data = json.load(f)
        
        self._logger.info(f"Read {len(data)} tfx from {tfx_json_file}")
        
        variant_transcripts = []
        
        for x in data['transcriptEffects']:
            if not x['cdnaTranscript']:
                count['skip_no_transcript'] += 1
                self._logger.info(f"Skipping variant that doesn't have transcripts: {x['chromosome']}-{x['position']}-{x['reference']}-{x['alt']}-{x['cdnaTranscript']}")
                continue
                        
            v = self._get_variant_transcript(x)            
            variant_transcripts.append(v)
            count['add_refseq_transcript'] += 1
        
        self._logger.info(f"{count}")
        return variant_transcripts
    
    def write(self, out_filename, variant_transcripts: list[VariantTranscript]):
        """
        """
        normalized_writer.write(out_filename, variant_transcripts)
        self._logger.info(f"Wrote {len(variant_transcripts)} variant transcripts to {out_filename}")

def _parse_args():
    parser = argparse.ArgumentParser(description='Convert Transcript Effects output to a csv file')
    parser.add_argument("--version", action="version", version="0.0.1")
    parser.add_argument("--in", help="File generated by Transcript Effects (json)", dest="input", required=True)
    parser.add_argument("--out", help="Normalized Tfx output file (csv)", dest="output", required=True)
    args = parser.parse_args()
    return args    

def main():
    from nomenclature_comparison.util.logger import setup_logging
    setup_logging(level=logging.INFO)

    args = _parse_args()

    norm_tfx = NormalizeTfx()
    
    variant_transcripts = norm_tfx.get_variant_transcripts(args.input)
    norm_tfx.write(args.output, variant_transcripts)
    
if __name__ == '__main__':
    main()                
        